iridl/python-maprooms

- onset_maproom/calc.py
Also includes seasonal_sum to illustrate how could be used to make "seasonal" functions.
The original plan was to make a generic function that will split 1D daily data into 2D daily data by days and years and select a subset of days defining a season. Thus allowing to perform analysis on the days dimension to obtain yearly series of a seasonal quantity and thus be able to reproduce a lot of popular Ingrid functions ([e.g.](http://iridl.ldeo.columbia.edu/dochelp/Documentation/details/index.html?func=flexseasonalfreqGT) and including onset date).
It turns out that xarray offers a [grouping function](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.groupby.html) and more specifically by [bins](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.groupby_bins.html) that …
> first try at a function to break 1D-daily into 2D for seasons

- fbfmaproom/fbfmaproom-sample.yaml
Note that the year range was set incorrectly before. We have probably been misinterpreting the results until now. I will send an email to everyone about this with more details.
> Add forecasts for DJF 2022 to Madagascar

- fbfmaproom/fbfmaproom.py
The map is supposed to display the shape of the selected region, but we broke that a while ago and didn't notice. This fixes it.
> Restore outline of selected shape

- onset_maproom/tests/test_calc.py
A small example to illustrate writing automated unit tests. Gotta start somewhere.
These are a lot like the the print statements that Rémi has left commented out in a few places. They're a record of the things we checked during development to convince ourselves that a function behaves the way we expect. The difference between Rémi's print statements and automated tests is that the automated tests include expected outputs, and each test tells us clearly whether the actual output matches the expected output. We can run lots of these tests in a small amount of time (typically hundreds per second), which means when we make a change and accidentally break something, we can find out about it almost immediately, rather than days or years later when a user reports it.
To run the tests,
- Activate …
> First test

- fbfmaproom/fbfmaproom-sample.yaml
- fbfmaproom/fbfmaproom.py
Trying to make it less onerous for a developer to keep his configuration file up to date.
- fbfmaproom-sample.yaml is now geared towards developers, rather than being a prescription for how it should be configured in production.
- You can now set CONFIG to a colon-separated list of yaml files, where values set in files that come later in the list override values set in earlier files. Now you can use fbfmaproom-sample.yaml directly, rather than maintaining a separate copy that you have to update every time the sample file changes.
> Easier configuration file management

- fbfmaproom/__about__.py
- fbfmaproom/fbfmaproom.py
- fbfmaproom/tests/test_fbfmaproom.py
to acommodate NaN as the missing value indicator (ints have no NaN value).
> download_table: represent bad_year as float rather than bool

- fbfmaproom/__about__.py
- fbfmaproom/fbfmaproom-sample.yaml
- fbfmaproom/fbfmaproom.py
I had previously made a change that was supposed to allowe missing values in the bad_years column, but I hadn't tested it yet. A bug became apparent when I tried extending the Ethiopia table to 2022.
Also moving dev server interface and port to the config file so we don't have to change it in fbfmaproom.py and risk accidentally committing the change.
> NaNs in table; Ethiopia December issue

- fbfmaproom/__about__.py
- fbfmaproom/fbfmaproom.py
- fbfmaproom/tests/test_fbfmaproom.py
@jturmelle reported that the following trigger check URL fails with a 500 error:
https://iridl.ldeo.columbia.edu/fbfmaproom2/pnep_percentile?country_key=malawi&mode=0&issue_month=10&season_year=2021&freq=30.0&season=season1&prob_thresh=30.314374923706055&region=152
@kgraaf reviewing this seems like as good a place as any for you to get your feet wet with the FBF application.
> Fix bug in trigger check endpoint

- fbfmaproom/__about__.py
- fbfmaproom/fbflayout.py
- fbfmaproom/fbfmaproom.py
This solves the issue of erroneous forecast raster data being "left behind" when updated to a month for which there is no forecast
> set pnep url to be blank when no forecast is available

- fbfmaproom/__about__.py
- fbfmaproom/fbflayout.py
- fbfmaproom/fbfmaproom.py
Souha says people want to see regional borders drawn over the forecast data to help them understand out what part of the country they're looking at. They would like this done quickly as people are using it right now.
I want to continue refining the implementation (see TODO), but this version didn't take much time and I think it's good enough for now.
The vulnerability choropleth looks a little weird because the border rendering that happens on the back end doesn't exactly align with the rendering that happens on the front end; but we plan to get rid of the choropleth anyway and replace it with markers of varying size, so I don't think that's worth fixing.
> Draw borders on top of forecast layer to help users get their bearings

- fbfmaproom/fbf-update-data.py
Rémi made a new version of the forecast catalog entry last month, and it seems like I must have generated the zarr from his version, but I neglected to update this script with it.
Since I have no record of how I generated the zarr that's currently in prod, we should carefully compare it with the new one before overwriting it. It should be identical except for the addition of the February forecast.
We don't need to do a release/deploy for this, as the only file being changed is one that's not used in production.
> Niger forecast v2

- onset_maproom/environment.yml
- onset_maproom/environment_linux.yml
- onset_maproom/layout.py
- onset_maproom/maproom.py
- onset_maproom/widgets.py
Updates onset maproom to work correctly with newer version of the bootstrap components. Also fixes deprecation warnings.
- Downgraded environment to Python 3.9 to fix rasterio error
- Upgraded environment to v1 of Dash Bootstrap Components
- Fixed deprecation warnings by switching to importing from dash instead of dedicated packages (should have identical behavior)
- Switched `no_gutters` parameter to using bootstrap `g-0` class
- Switched deprecated `bs_size` parameter to `size`
- Removed `FormGroup` component and code designed to support it
- Added padding that was eliminated by removal of `FormGroup`s
> Python dependency updates

- fbfmaproom/assets/style.css
- fbfmaproom/environment.yml
- fbfmaproom/environment_linux.yml
- fbfmaproom/fbflayout.py
- fbfmaproom/fbfmaproom.py
- fbfmaproom/tests/test_fbfmaproom.py
removed offending code that prevented bootstrap components upgraded and pinned necessary versions of pandas and shapely
Two packages had to be pinned to specific (old versions) so that the environment could be safely added to:
1. Pandas:
Newer versions of Pandas do not appear to work correctly with queuepool. In particular, how that package forms SQL query objects needs to be updated. Hopefully the solution here is to either send Igor a issue or to migrate to a different connection pooling library    
2. Shapely:
Shapely changed how looping over geometries works in the newer version and Pingrid relies on the old functionality. It is unclear to me whether using the .geoms property has the same behavior as the "built in" iterator the old version had. As we may migrate way from Pingrid and …
> Updated fbf packages

- onset_maproom/environment_linux.yml
The one Kevin built a couple weeks ago is now no longer installable--the solver reports conflicts. We have yet to figure out why, but I think something must have changed upstream, like a package we were using got tagged "broken" and thus the solver no longer considers it valid. This lack of reproducibility is a major concern and must be addressed, but that's not what I'm doing in this PR. I'm just working around the problem so we can keep moving on the enactsmaproom project.
> Rebuild environment_linux.yml

- fbfmaproom/fbfmaproom-sample.yaml
I wrote the vuln SQL fragment such that it does not generate an extraneous query to the DB and contains no rows but that each column has the right type, along with a comment explaining this.
> Add commune level to the Niger FBF maproom

- onset_maproom/docker/httpd.conf
We don't get any real parallelism from threads, probably due to the GIL. We changed to processes for the dev configuration in PR #70, but I forgot to do the same for the prod configuration.
> Use processes instead of threads in onset apache config

- onset_maproom/Dockerfile
When I released the new version with multiple process configuration for apache, I noticed that the image is enormous (4GB) and takes forever to upload/download. This PR applies the multi-stage pattern that we already use in fbfmaproom.
Also made a couple other Dockerfile improvements while I was in there. Read commit-by-commit.
> Two-stage build for onset maproom

- fbfmaproom/fbfmaproom.py
- fbfmaproom/tests/test_fbfmaproom.py
Internal representations of months were 0-based month numbers (0 = January) in some places, and indexes into the issue month list (0 = whatever month is listed first in the config file) in others. This makes it consistently 0-based month numbers everywhere.
1-based everywhere would probably be better (less mental gymnastics when debugging), but that's a bigger change that I'll leave for another day.
> Eliminate confusing reference to issue months by position in the list

- fbfmaproom/__about__.py
- fbfmaproom/fbfmaproom.py
Two-line fix for a mistake in https://github.com/iridl/python-maprooms/pull/96. @kgraaf please review ASAP.
I will add a test for this behavior later, but I want to get the fix in fast.
> Fix bug where "worst" attribute was ignored

- fbfmaproom/fbf-update-data.py
Get Niger ENACTS straight from the source, rather than using the copy of it that PyCPT made. That way, when the source gets updated with data for recent years, we can get it without rerunning PyCPT.
Had to add authentication to the download script because this dataset is protected.
> Change Niger ENACTS URL; add authentication to download script

- fbfmaproom/docker/httpd.conf
- fbfmaproom/fbfmaproom-sample.yaml
- fbfmaproom/fbfmaproom.py
We already did this for the onset maproom and it improved performance a lot. Not sure it will make as big a difference here, because the FBF application is less CPU intensive, but it allows me to load the Niger map successfully on my laptop, whereas flask crashes if I try to do that with threading enabled.
It still seems to use an inordinate amount of memory, so I'm going to continue trying to figure that out, but this is something that we ought to do anyway and it unblocks me for now.
> Use processes instead of threads for fbf

- fbfmaproom/fbf-update-data.py
- fbfmaproom/fbfmaproom-sample.yaml
- fbfmaproom/fbfmaproom.py
- fbfmaproom/fbftable.py
- fbfmaproom/tests/test_fbfmaproom.py
@kgraaf Dan would like to share this with partners by tommorrow, so please review promptly.
In a separate branch I'm working on per-column formatting rules, but that will take more time. For now, we have a single formatting function that handles both integer and timedelta columns. It doesn't cover all possible cases, just the ones we need right now.
I made an [inventory](https://docs.google.com/document/d/1UOcAsQkA9y99eIa_um12K8gRD7BKIVtBSgnXa63W75g/edit#) of the obs datasets for all the countries and confirmed that they all have correct units metadata. After sending this, I'm going to work on exposing the units in the table heading, and will push another commit if that's successful. We should deploy this by tomorrow with or without that addition.
Please review commit-by-commit and see …
> Display underlying obs values instead of ranks

- fbfmaproom/Dockerfile
- fbfmaproom/__about__.py
- fbfmaproom/docker/entrypoint
- fbfmaproom/docker/httpd.conf
Shouldn't be putting site-specific info in the container like this, but it's the 11th hour. In the not too distant future we're going to have to implement user and password management for real, at which point we can get rid of this.
> Ugly hack to put Lesotho FBF behind a password

- fbfmaproom/fbfmaproom.py
To match display in the table.
Unfortunately the precision of the table column is set in the config file but this is hard coded. Might try to resolve that at some point.
https://trello.com/c/qM9Xv7Wd/25-reduce-displayed-precision-of-threshold
> Display only one place after the decimal in threshold

- fbfmaproom/fbf-update-data.py
- fbfmaproom/fbfmaproom-sample.yaml
Fixes a problem with the Moyale woreda, which straddles the border between Somali and Oromia. See https://trello.com/c/1wuQcqvi/46-error-during-ethiopia-admin-3-download
Need to do the same for all the obs datsets eventually, but this one is urgent.
> Extend Ethiopia rain datsets to cover same spatial extent as forecast

- fbfmaproom/assets/style.css
- fbfmaproom/fbflayout.py
Makes the table fill the available space, rather than using a fixed height of 700px. The impetus for working on this was a [complaint](https://trello.com/c/BnvCHqFf/29-remove-not-official-govt-maproom) about the "Not an official government maproom" disclaimer appearing on top of the table under certain circumstances, but having the table stretch vertically is something I've wished for independently for a long time.
I recommend reading one commit at a time.
> Make table fill available vertical space

- fbfmaproom/fbf-update-data.py
The new forecast covers all of Madagascar, for for now FBF is still using only the four southernmost regions.
> New Madagascar forecast

- fbfmaproom/assets/style.css
This rule was here to avoid a double-wide bottom border, since there's also a border around the whole table. But now that the table stretches to fill the available space, sometimes the last row doesn't reach the bottom of the box, and then it looks weird:
With this fix and a tall window:
With this fix and a short window (you can see the double-wide bottom border):
> Draw border under last table cell

- pingrid.py
in case the subset is only 1 pixel wide/tall.
This was the root cause of https://trello.com/c/1wuQcqvi/46-error-during-ethiopia-admin-3-download . If I'd realized it was going to be this easy to fix, I would have done this instead of extending the spatial domain of the obs variables. :-(
> Calculate spatial resolution before spatial subsetting

- fbfmaproom/fbf-update-data.py
- fbfmaproom/fbfmaproom.py
This significantly reduces the memory used by the Niger maproom, and makes Niger tiles load in about 500 ms compared to 1600 with the original chunking. It will probably help with the other countries too, but Niger was the biggest offender, since it has the biggest dataset (area x resolution).
Also including a couple small, unrelated changes to things I noticed while investingating the problem.
BTW after this change, the majority of the time used by the tile endpoint is spent querying the db to get the clipping shape. I have ideas about how to optimize that, which I will try in another branch.
> Rechunk for faster tiles

- fbfmaproom/fbfmaproom.py
- onset_maproom/maproom.py
- pingrid.py
We've been spending 400ms on every tile, including tiles where there's no data, because fetching the clipping shape from the db is strangely expensive. (I wonder if that's because the shapes are in a "foreign table.") In this PR we defer loading the shape until we know we need it, getting the time for an empty tile down to 60ms.
> Short circuit tile generation for tiles outside of dataset 

- fbfmaproom/assets/style.css
- fbfmaproom/fbflayout.py
- fbfmaproom/fbfmaproom-sample.yaml
- fbfmaproom/fbfmaproom.py
- fbfmaproom/fbftable.py
- fbfmaproom/tests/test_fbfmaproom.py
Implements https://trello.com/c/2ieEQPol/32-ability-to-trigger-on-an-obs-column-multiple-forecasts . Also including a fix for https://trello.com/c/iCRBXlvW/43-default-year-for-trigger-year because it would have conflicted with this if I did it on a separate branch.
This is built on top of PR #133, which is useful and deployable on its own, so please review that one first.
I suggest reviewing commit by commit.
> Support triggers on any column, and potentially multiple forecasts

- fbfmaproom/fbf-update-data.py
- fbfmaproom/fbfmaproom-sample.yaml
- fbfmaproom/fbfmaproom.py
See https://trello.com/c/vNhjaEFN/59-display-entire-forecast-for-madagascar . We're still only doing FBF in the southernmost regions, but they want to see the visual representation of the forecast for the whole country. This seems like the cheapest way to do it.
> Turn off clipping for Madagascar, display forecast for whole country

- fbfmaproom/fbfmaproom-sample.yaml
- fbfmaproom/fbfmaproom.py
I'm sick of having to bump the year_range for every country once a year. If you don't want a forecast to show up yet, just don't install it in the production dataset.
> Don't specify final year in config file

- fbfmaproom/environment.yml
- fbfmaproom/environment_linux.yml
- fbfmaproom/fbfmaproom-sample.yaml
- fbfmaproom/fbfmaproom.py
- fbfmaproom/tests/test_fbfmaproom.py
- onset_maproom/config-anacim-senegal.yaml
- onset_maproom/config-ghana-met.yaml
- onset_maproom/config-mali-meteo.yaml
- onset_maproom/config-nma-ethiopia.yaml
- onset_maproom/config-zambia-md.yaml
- onset_maproom/environment.yml
- onset_maproom/environment_linux.yml
- onset_maproom/maproom.py
- pingrid.py
- subseas_flex_fcst/environment.yml
- subseas_flex_fcst/environment_linux.yml
This is for @kgraaf to review; tagging the others as an FYI.
Igor's queuepool library now has three strikes against it:
- When the database server goes down for a while, the pool never recovers, even after the database comes back on line. We have to manually restart all of the python services to get them back.
- It breaks under heavy concurrent load. We get error messages like `psycopg2.OperationalError: lost synchronization with server: got message type "3", length 1630681443`. (This showed up as a side-effect of a bug that caused multiple db queries to be issued on each tile request.)
- It's not packaged for conda, so we have to install it with pip.
All of these problems could surely be fixed, but rather than spending time on that, I would prefer to switch to SQLAlchemy, which is the de …
> Remove queuepool

- subseas_flex_fcst/config-sample.yaml
- subseas_flex_fcst/layout.py
- subseas_flex_fcst/maproom.py
Based off of the email thread regarding lead times, I gathered that it did not matter directly how we represented the leads at least within the data itself, so my approach was:
Use the lead time representation and map those to some arbitrary lead time values that the user can configure both of in the configuration file. I tried to make it as flexible as possible to apply to other datasets.
Then in the maproom itself it allows the user to select from target date ranges.
> Change lead time representation in subs maproom

- fbfmaproom/__about__.py
- fbfmaproom/assets/style.css
- fbfmaproom/fbflayout.py
- fbfmaproom/fbfmaproom-sample.yaml
- fbfmaproom/fbfmaproom.py
- fbfmaproom/fbftable.py
- fbfmaproom/tests/test_fbfmaproom.py
- pingrid.py
The goal of this PR was to give the user control over whether the forecast for the upcoming season was included in the threshold calculation or not. While working on that I also did some refactoring, and changed to a different Bootstrap theme because the color choices of the one we were using seemed unconventional and disturbing. Please read commit-by-commit.
> Toggle to include/exclude upcoming/current season in threshold calculation.

- fbfmaproom/fbfmaproom.py
When you click outside the project area it's supposed to blank out the table, but currently it doesn't. I probably broke this in my recent PR where I refactored the code that pulls shapes from the db.
> Fix regression in error handling when click outside forecast area

- onset_maproom/config-anacim-senegal.yaml
- onset_maproom/config-ghana-met.yaml
- onset_maproom/config-mali-meteo.yaml
- onset_maproom/config-nma-ethiopia.yaml
- onset_maproom/config-zambia-md.yaml
- onset_maproom/layout.py
- onset_maproom/maproom.py
This will print under the map the "label" of the highest level of admin overlay that is being checked. The "label" typically contains the name of the lower levels of admin levels they belong to -- to be formed in the config file where the sql query is.
So my code starts with a default text to print, and it is overwritten by the last hover_feature entry that is not None. Maybe it's not efficient?
This is using Dash's ALL and component id as dictionary, which allows both to:
-- not crash at start as the admin layers may not be known
-- get more than one input at a time
Also I didn't do any styling. Recommendations welcome.
> mousing over map prints label of highest checked admin overlay

- fbfmaproom/fbfmaproom-sample.yaml
Note that I had to use explicit dummy vuln queries because the default query assumes that the key is an int but in this case (and many others) it's varchar.
They only sent us adm3 shapes, so the other levels are unions of those.
> New shapes for southern oromia

- fbfmaproom/tests/test_pingrid.py
- onset_maproom/maproom.py
- pingrid/impl.py
Screenshots from the KMD monthly climo maproom (which is not in this repo; I already made the fix in the KMD copy):
Before:
After:
> Fix incorrect display of values outside colormap range

- fbfmaproom/tests/test_pingrid.py
These were broken by https://github.com/iridl/python-maprooms/pull/244/files, which changed how we interpret the ingrid colorscale representation.
> fix colormap tests

- fbfmaproom/fbfmaproom-sample.yaml
A duplicate of an existing entry but with lower_is_worse set to no instead of yes, as a first attempt at highlighting years where there were probably floods. Currently under review on shortfin01.
> Niger ENACTS flood proxy

- enacts/config-bd.yaml
- enacts/config-gmet.yaml
- enacts/config-mali.yaml
- enacts/config-nma.yaml
This is adding to the config files for countries to fix a bug in printing the raster data. When the top level geometry is a subdivision of a country then the raster data will only print for a single subdivision. So adding a national (country level) geometry allows for the whole raster layer to be printed.
> adding national shapes so that raster data will print for whole country

- fbfmaproom/fbfmaproom-sample.yaml
In one branch we renamed this field, and in another branch we added some more datasets, resulting in a conflict that git couldn't detect automatically.
> Finish renaming config field

- enacts/onset/maproom.py
This is another error that doesn't have to do with the bug where a previous line plot persists after a callback. Let's merge this to clear the path.
> removed one too many tailing points

- enacts/onset/maproom.py
I documented a couple of options in PR #302 
It seems that basic histograms is the way to go...
> histograms is better for time series with missing values

- fbfmaproom/Dockerfile
- fbfmaproom/__about__.py
- fbfmaproom/docker/httpd.conf
- fbfmaproom/docker/passwords
We're going to run a second instance of the fbfmaproom application at iridl/fbfmaproom2-staging, using /data/aaron/fbf-candidate instead of /data/aaron/fbf, and with password protection on all countries, to support testing of new datasets (not new code versions) by external users.
~Password hashes clearly don't belong inside the container. I'm working on generating httpd.conf and /etc/httpd/passwords from a template at runtime, but I want to make the functionality available ASAP so I'm starting with this quick-and-dirty version.~ [edit: authorization rules and password hashes are now mounted into the container from the host.]
Accompanying dlconfig PR: https://bitbucket.org/iridl/dlconfig/pull-requests/215?t=1
> Password protection for staging URLs

- fbfmaproom/__about__.py
- pingrid/impl.py
I guess I forgot to test the vulnerability layer before approving the colormap change. It's currently displaying shades of blue rather than shades of yellow/orange.
> FBF: Fix vuln colorscale--opencv expects bgr not rgb.

- enacts/config-defaults.yaml
- enacts/config-sng.yaml
- enacts/wat_bal/agronomy.py
- enacts/wat_bal/maproom_monit.py
I ran into a couple of issues in order to this and what I propose here is probably the start of the discussion rather than the final solution. I am also going to add some comments to point out some specific problems that led me to do some changed.
rr_mrg's and taw's X/Y are the same by design but they respectively are double and single precision. That caused the tiling to create tiles of different sizes (by 1 point), resulting in water balance algo to fail (see more details below -- but water balance algo expects coordinates of same name to be identical througout its inputs).
converting rr_mrg's X/Y to single fixed the tiling problem, but water balance was still failing. Turns out that one of the two sets of X/Ys had many values with tailing ...00001. Yet, there are a series of broadcast …
> taw read from file depends on X/Y instead of constant

- fbfmaproom/tests/test_pingrid.py
This test is failing because we didn't update it when we introduced the new colormaps.
> fix test_tile

- enacts/config-sng.yaml
It turns out I also have ENACTS daily precip in /data/remic/mydatafiles/ but maybe we should just stop writing in our locations and rather write to some common place at some point?
> converting daily et0 to zarr

- enacts/calc.py
- enacts/onset/tests/test_calc.py
Soooo... I think this is the unit-step we are looking for for a cessation date search loop. BUT... it's not super intuitive so definitely needs other eyes on it.
Operating in timedelta domain. The loop on time will also have to update the spell length which is the criteria to find onset. And if the input is rain rather than readily available soil moisture, the loop will also have to get an updated sm. Since spells typically involve more than 1 day, that loop will have to save just the bit of history (e.g. 5 days) it needs to evaluate spell length.
Let me know if I (don't) make any sense.
> unit step for cessation date search

- fbfmaproom/__about__.py
- fbfmaproom/fbfmaproom.py
Fixes an annoyance that caused errors to persist in the browser even after the root cause had been fixed on the server.
> Don't put garbage in location querystring after an error

- enacts/calc.py
- enacts/tests/test_calc.py
I eliminated duplication by folding the initialization into the loop. I also split `cess_date` into two functions `cess_date_from_sm` and `cess_date_from_rain`, in the hopes of making them easier for the programmer to understand.
Seeing the result of these changes, I'm happy with two functions instead of one, but I'm not sure about eliminating the duplication. Is this version harder to understand?
> cess_date refactoring

- enacts/flex_fcst/cpt.py
- enacts/flex_fcst/layout.py
- enacts/flex_fcst/maproom.py
- enacts/flex_fcst/predictions.py
This is not pretty but that's what we get for rushing work on top of unfinished work (aka cleanly separating files reading, dates selecting, dates formatting).
I gave up on getting the Target date from data so it's hard-coded. It's ok enough because the case reading pycptv2 nc files assumes one app per target date.
It seems that because CONFIG["y_transform"] is used as default value of a function, it needs to be defined. So it's still there in the config (will push that PR soon soon).
This should do for tomorrow's demo. Will have to clean it all up soon because next time we need to add a layer, it will likely be too ugly.
EMI tsv case still works.
> adapting to a case of reading pycptv2 nc files

- fbfmaproom/fbf-update-data.py
- fbfmaproom/fbfmaproom-sample.yaml
See https://trello.com/c/0QENK7jJ/20-set-up-niger-september-total-chirp-and-enacts-mon
Can be seen on the test server (VPN required): http://shortfin01.iri.columbia.edu:9999/fbfmaproom/niger?mode=0&map_column=pnep&season=season1&predictors=pnep+enacts-mon-rainfall-sep+chirp-rainfall-sep&predictand=bad-years-v3&year=2023&issue_month=jun&freq=30&severity=0&include_upcoming=false&position=%5B17.025%2C8.025%5D&show_modal=false
Sari needs it for Tuesday.
> September rainfall monitoring datasets for Niger

- enacts/wat_bal/agronomy.py
- enacts/wat_bal/tests/test_agronomy.py
equations look all the same in Eunjin python code and in FAO doc (and in my code) however, FAO doc indicates that:
"For the winter months in latitudes greater than 55° (N or S), the equations for Ra have limited validity."
I assume that is where the arccos error came from (I actually could go as far as 70 or 75 before getting it).
> eq invalid at lat higher than 55 in Winter months

- fbfmaproom/tests/test_pingrid.py
- pingrid/impl.py
We get different numbers in the same column depending on what other columns are in the table, e.g.
vs.
This is because when we put DataArrays with non-aligned X and Y coordinates into the same Dataset, the resulting X and Y coordinates are no longer regularly spaced, violating an assumption we made in pingrid. The quick fix I'm doing here is to drop coordinate values where the variable is all NaN, to get back to the original coordinate, but in the longer run we should stop putting non-aligned variables into the same Dataset. If nothing else, it's a waste of space, because we have to store a lot of NaNs.
@remicousin you don't need to review the change in context, but you should be aware of the issue.
I have a test server running on shortfin01:9998, waiting for Jeff to open that port so we …
> Quick fix for problem of irregular coordinates

- enacts/flex_fcst/maproom.py
When loading the EMI configuration, the map title doesn't appear, and the following error appears in the console:
```
[2023-12-13 12:03:11,267] ERROR in app: Exception on /python_maproom/flex-fcst/_dash-update-component [POST]
Traceback (most recent call last):
File "/home/aaron/scratch/miniconda3/envs/enactsmaproom/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/home/aaron/scratch/miniconda3/envs/enactsmaproom/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/aaron/scratch/miniconda3/envs/enactsmaproom/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
rv = self.dispatch_request()
File …
```
> Fix bug in write_map_title

- enacts/flex_fcst/maproom.py
Originally in this PR #383 where there are also valuable conversations around how proper metadata rather than config file should inform triggering the case or not.
flex_fcst had been extensively changed since that PR so it was simpler to close it and apply the changes in a new PR rather than rebasing.
> rainfall can't be negative

- enacts/README.md
When reviewing your recent PR, I noticed that the instructions for publishing a new container were inappropriately copied from fbfmaproom2.
> Update container build instructions

- enacts/flex_fcst/cpt.py
Allows issue month dirs to be at the top level instead of inside a subdir per season, in the case where there's only one season. The structure with the intermediate dir is still accepted too.
> PyCPT forecast file structure

- fbfmaproom/fbfmaproom.py
This addresses Dante's comment https://trello.com/c/Y1Xc6Lxt/47-djibouti-new-bad-years#comment-660eec71af54a1ce48f40e17
I think this was originally set to 3 instead of 2 because a boolean column can be 0.0, 1.0, or NaN. But in fact, the NaNs are removed in line 603, so we can lower it to 2 without changing the behavior.
Tested on Djibouti: http://shortfin01.iri.columbia.edu:9998/fbfmaproom/djibouti
- with the slider at 20%, only 6s are highlighted
- with the slider at 30%, 6s and 9s are highlighted
- with the slider at 35%, everything is highlighted.
Also tested the boolean bad years in Ethiopia and Niger, no change in behavior (the years marked "Bad" are all highlighted, regardless of the position of the slider).
> Boolean columns only have two values

- enacts/README.md
@remicousin you asked in the past how to find out what was the most recent version of the enactsmaproom docker image, and I didn't know of anything better than asking me. I don't know if this is new or (more likely) I just didn't find it before, but here's the right answer.
> emactsmaproom README: how to find most recent container image

- fbfmaproom/data-conversion-scripts/zarrify-bad-years.py
- fbfmaproom/data-conversion-scripts/zarrify-forecast.py
- fbfmaproom/fbf-update-data.py
- fbfmaproom/fbfmaproom-sample.yaml
Initial commit for Guatemala May forecast maproom
> Guatemala May initial setup

- enacts/flex_fcst/maproom.py
- enacts/onset/maproom.py
- enacts/wat_bal/maproom_monit.py
> sufficient set up per CSC case

- pepsico/app_calc.py
- pepsico/projections/layout.py
- pepsico/projections/maproom.py
This made me have the colorscale be vertical to accommodate sometimes long units. It would make sense that colorbar could have a label or title in which to put the units ones, but it doesn't have that. The way to tailor further with having maybe the units on only one tick would be to create the entire ticking manually and feed it to colorbar. But that sounds tedious, at least for now.
Also made me revisit a bit the map_attributed factored out function since now it needs data all the time to read units. Or at least that workflow seemed to make more sense to me.
> bringing units to the colorscale

- fbfmaproom/fbfmaproom-sample.yaml
Modified the fbfmaproom/fbfmaproom-sample.yaml file to include the new version of the Niger Forecast v5. On running the map tool locally, you can see the forecast.
> Added Niger Forecast v5

- fbfmaproom/Dockerfile
- fbfmaproom/__about__.py
- fbfmaproom/pixi.toml
The CentOS 9 container wouldn't run on geo1, so back to CentOS 7 until we can upgrade the servers. I'm keeping pixi.
> Back to CentOS 7

- enacts/calc.py
- enacts/config-test-enacts.yaml
- enacts/config-test-synt.yaml
- enacts/crop_suitability/maproom_crop_suit.py
- enacts/enactstozarr.py
- enacts/monthly/maproom.py
- enacts/onset/maproom.py
- enacts/wat_bal/maproom_monit.py
The first commit splits the reading business from the Maprooms for ENACTS data only.
The second commit introduces the case of synthesizing daily ENACTS data if no data to read. Introducing a new test config file for onset and CSC (because monthly uses dekadal and water_balance needs also fake soil data). But the whole can be tested on the Senegal test case to test the 1st commit.
At the moment, I can't guarantee tmin < tmax since they are generated independently... Something to think about how much it matters (the functions that care about it might be dealing with the case...)
Next steps would be a function to make dekadal out of daily and test the case and apply to monthly; then fake soil data to apply to wat_bal; then consider what to do with respect to shapefiles to be entirely …
> Splitenactsread

- fbfmaproom/fbfmaproom-sample.yaml
Hi Aaron, can we have this new version in the public sever? It is missing some years but the forecast can be calculated for 2025 so it is helpful to have it available.
> adding v4 of the jja forecast for Gautemala jja

- enacts/calc.py
- enacts/crop_suitability/maproom_crop_suit.py
- enacts/flex_fcst/maproom.py
- enacts/maproom_utilities.py
- enacts/monthly/maproom.py
- enacts/onset/maproom.py
- enacts/wat_bal/maproom_monit.py
This is a bunch of factorization for us to get ready to split shapes reading from apps and apply the case of fake shapes. But I am not sure at what level we'll fork the fake case... at sql/db? at GeoJSON? create dummy geom from scratch?
The commits kind of make sense in chronological order except I forgot to add the new file which should have been in the 2nd commit, and later commits update the former so... might make more sense to look at the final thing. Commits' comments tell you the story.
> Splitshpandmapping

- fbfmaproom/fbflayout.py
- fbfmaproom/fbfmaproom-sample.yaml
The Djibouti logo wasn't appearing because the filename in the config file didn't match what we had on the server. (FYI the files on the server are managed in a different repo that only DL team has access to. The plan is to move each country's logo file into that country's python_maproom repo when we install the application on their server.)
While I was at it, I also decided to stack the title on top of the logo to save some space. Before:
After:
> Fix Djibouti logo; rearrange title and logo to save space

- pepsico/maproom_utilities.py
- pepsico/projections/maproom.py
Factored out the things constantly used across python maprooms. Meant to avoid constant copy and paste. Can potentially be moved one level up to apply also to enacts if ever helpful to do so. The fact that there can a control triggers a reinitialization of the map with new set of admin to use makes it a bit messier and the only difference with enacts. Can revisit and clean that up later if need be.
> Splitpepsico

- fbfmaproom/assets/style.css
- fbfmaproom/fbflayout.py
- fbfmaproom/fbfmaproom-sample.yaml
- fbfmaproom/fbfmaproom.py
- pingrid/impl.py
I updated the season page so it is a dropdown of pages for related season pages of the same country. This replaces the current season dropdown which currently does not change the values.
I didn't remove the current season code because the config values are still used as static values, when it is refactored to be in a single page I can cleanup this code. For now, I've stored the season values in a hidden dropdown
Open up the page for madagascar
Select a season for a different page and confirm it navigates correctly
> Jpng.merge seassons to single page

- fbfmaproom/fbfmaproom-sample.yaml
Hi @aaron-kaplan , new attempt here. Thanks for the review, I added  the version to be displayed as default this time and seems like there's no conflicts.
> New versions for JJA (v6) and ASO(v4) added for Guate_AA, new attempt
