iridl/python-maprooms

onset_maproom/calc.py
renaming (random) onset_date that will become seasonal_onset_date
I guess for consistency...
=> adding onset_date in xarray

fbfmaproom/fbfmaproom-sample.yaml, fbfmaproom/fbfmaproom.py
This should make it less of a pain to keep our config files in sync with the sample.
=> Put path to data dir in one place instead of many

fbfmaproom/fbfmaproom.py
=> Adding port

fbfmaproom/__about__.py, fbfmaproom/fbflayout.py, fbfmaproom/fbfmaproom-sample.yaml, fbfmaproom/fbfmaproom.py, fbfmaproom/tests/test_fbfmaproom.py, pingrid.py
Past discussion and todos [on bitbucket](https://bitbucket.org/iridl/x24-vector/pull-requests/53).
Add NDVI and WRSI columns to the table. Rahel will send us WRSI data. We will need to calculate NDVI spatial averages. Ideally we should render Rain, NDVI and WRSI in a single column with dropbox to switch between Rain, NDVI and WRSI
**REMEMBER TO UPDATE CONFIG IN DLCONFIG WHEN YOU RELEASE**
=> Second attempt to implement multiple observation datasets

fbfmaproom/fbfmaproom-sample.yaml
=> Extend FBF Niger to 2022 season

fbfmaproom/fbflayout.py, fbfmaproom/fbfmaproom.py
Ensures that the table will not show erroneous data
=> handle condition where no data exists for current location

fbfmaproom/fbfmaproom.py, fbfmaproom/tests/test_fbfmaproom.py
Also removing some dead code, and fixing a test that was broken by the previous PR. (We need CI so that we don't forget to run the tests before merging.)
=> Another bug in trigger check endpoint

fbfmaproom/Dockerfile, fbfmaproom/__about__.py, fbfmaproom/environment.yml, fbfmaproom/environment_linux.yml, fbfmaproom/environment_macos.yml, fbfmaproom/fbflayout.py, fbfmaproom/fbfmaproom.py, fbfmaproom/tests/test_fbfmaproom.py, pingrid.py
Before we invite others to start generating tiles, I wanted to simplify the tiling API, with two goals: make it easier to use, and encapsulate the use of OpenCV so that we're not tied to it permanently.
~I still want to try to simplify the handling of colormaps, but I couldn't get that done today. I'm submitting what I have so we can merge it quickly and minimize divergence between branches.~
This PR is broken up into logically distinct commits. I recommend reading one commit at a time.
=> Simplify tiling

fbfmaproom/__about__.py, pingrid.py
I spent some time getting my head around the tiling code, and then made some changes that I think will help me the next time I need to understand it. Removed some code that is never used, added some docstrings, and changed a couple function names to be more self-explanatory.
No change in functionality.
=> Make tiling code easier to understand

fbfmaproom/fbfmaproom.py, pingrid.py
When we fixed the problem of stale data appearing in the table or the map, we suppressed some potential errors that should be logged. Raising a more specific exception in the cases where we actually intended to suppress the message, so we can give them special treatment.
=> Revamp exceptions raised for client-side errors; log more errors

fbfmaproom/README.md, fbfmaproom/fbfmaproom-sample.yaml
table was added with wrong name to database originally, fixed and updated config
=> fixed niger commune table name

fbfmaproom/fbfmaproom.py, fbfmaproom/tests/test_fbfmaproom.py
=> Add worst_pnep column to csv download if freq is specified

fbfmaproom/fbfmaproom.py
The good news is that the tests caught this. The bad news is that apparently I forgot to run the tests. I really want to run them in CI, but currently a lot of the tests require the prod database, which won't be available in a CI environment. We need a test data fixture.
=> Fix download_table bug introduced in last release

fbfmaproom/fbflayout.py, fbfmaproom/fbfmaproom.py, fbfmaproom/tests/test_fbfmaproom.py, pingrid.py
Using a multi-select just above the table instead of buttons/menus within the table. This might not be the ideal UI, but it was quick to implement, which gives us a chance to try implementing triggers on obs before the deadline.
=> Multiple obs columns

fbfmaproom/fbfmaproom.py, fbfmaproom/tests/test_fbfmaproom.py
See the github issue linked in the comment for more info.
=> Remove workaround for dash-leaflet bug that has been fixed

fbfmaproom/fbf-update-data.py, fbfmaproom/fbfmaproom-sample.yaml
Will merge immediately because it's a rush job.
=> Add Madagascar OND ENACTS MON SPI; default to MON precip

fbfmaproom/fbf-update-data.py
So we're not constantly commenting and uncommenting stuff.
=> Accept dataset names on update script command line

fbfmaproom/fbfmaproom-sample.yaml, fbfmaproom/fbfmaproom.py, fbfmaproom/fbftable.py, fbfmaproom/tests/test_fbfmaproom.py
Turned out to be a big change for what seemed like a simple request, because the ENSO dataset covers multiple seasons while other other datasets all covered a single season each. But it's good because now we're closer to being able to merge the lesotho and lesotho-ond pages into one.
https://trello.com/c/mI1dEP6y/27-enso-column-optional
=> Make ENSO column optional

fbfmaproom/fbfmaproom.py, fbfmaproom/tests/test_fbfmaproom.py
Adding info about historical years; also moving the endpoint from /fbfmaproom2/export?country=lesotho to /fbfmaproom2/lesotho/export so the existing password protection rule will apply.
https://trello.com/c/Vv3Bxe7R/19-change-export-api-to-support-history
=> History API

fbfmaproom/fbflayout.py, fbfmaproom/fbfmaproom.py, fbfmaproom/pyproject.toml, fbfmaproom/tests/test_fbfmaproom.py, pingrid.py
I think this is all the "plumbing" work needed to support setting triggers on any column. The UI changes will follow in a separate PR. Also some unrelated improvements that I made along the way. Best read one commit at a time.
=> Backend changes to support multiple forecasts and triggers on obs

fbfmaproom/fbflayout.py, fbfmaproom/fbfmaproom.py
There are still a couple of warnings, but I think those are dash's fault, not ours. Will look into that separately.
=> Eliminate react errors in browser console

fbfmaproom/fbfmaproom.py, fbfmaproom/fbftable.py
Quick emergency fix, will think about how to prevent this in the future.
=> Fix failure on the 31st of the month

fbfmaproom/fbf-update-data.py
Companion to https://bitbucket.org/iridl/dlentries_nma/pull-requests/9/use-ond-forecast-from-data-aaron
=> Use copy of forecast in /data/aaron

fbfmaproom/fbflayout.py, fbfmaproom/fbfmaproom.py
https://trello.com/c/ytq0V45x/87-only-admin-name-on-picker-selection
While I was in there, I also fixed a couple things that have always bugged me:
- Now you can move the marker by clicking on a spot, in addition to the existing mechanism of dragging the marker.
- Added a loading indicator to the popup so it no longer displays the name of the previously-selected region while it's waiting for the callback to finish.
=> No vuln data in popup

onset_maproom/config-anacim-senegal.yaml, onset_maproom/config-nma-ethiopia.yaml, onset_maproom/layout.py, onset_maproom/maproom.py
A few minor things that has been requested by Tufa.
The one thing I could not figure out a good solution for was the min/max zoom option. I know it had been said that setting min/max zoom in the way I did was not a good permanent solution because it is dependent on screen size (I think was the reason?). I couldn't find a workaround yet. so pushed my changes with what I have for now.
The other thing I noticed that might be nice would be to have an option to view boundary names, perhaps when you mouseover? Since you can't really tell what you are looking at very well now. Just a thought...
=> Onset maproom minor improvements 

fbfmaproom/tests/test_fbfmaproom.py
One of my recent PRs broke a bunch of tests. Gotta get those tests into CI.
=> Fix broken tests

subseas_flex_fcst/layout.py, subseas_flex_fcst/maproom.py
Making a map title. I put it on top of the map which felt intuitive to me but I know the onset maproom has it on the bottom..
=> subs fcst map title

onset_maproom/agronomy.py, onset_maproom/docsrc/index.rst, onset_maproom/tests/test_agronomy.py
The very first part of the water balance step-wise function.
One thing I am not sure of is that I think the final result should be a Dataset. Should it be so at this stage? and if so, should then the inputs that belong the to the water balance Dataset be a Dataset too? Or should we deal with building a Dataset later?
Also, when I run the building of the documentation, I only get calc.py module. I am not sure what I am missing to get the agronomy.py module...
Next part would be either to introduce Kc.
=> simplest water balance step

pingrid.py, subseas_flex_fcst/layout.py, subseas_flex_fcst/maproom.py, subseas_flex_fcst/predictions.py
A couple of functions made to be reused.
=> Factoring out functions

onset_maproom/agronomy.py, onset_maproom/tests/test_agronomy.py
So... I was working on adding Kc to the step, until I realized it didn't really belong in the step. It belongs to the loop on doy that will feed another et to the step. Similarly, it made me realize that runoff also doesn't belong to the step. It doesn't even belong to the loop on doy since we know how to compute runoff from rainfall for all times.  So this PR removed runoff from the step.
The other element of the balance is Ks, that also doesn't belong to the step, but does belong to the loop.
So I believe next step from here is to make the loop function on doy. Then progressively incorporate the elements altered in loop.
Makes sense or I am starting to loose it here?
=> simpler step

subseas_flex_fcst/layout.py
I was going to tailor the text to what is in view, but it seems as simple for now to just generalize. If more options come up, it might be better then to move to tailored dynamic text.
Also, added text about S/L choices since they are now available.
=> generalizing descriptive text and adding hint towards changing S/L

pingrid/impl.py, subseas_flex_fcst/layout.py, subseas_flex_fcst/maproom.py
This is an attempts, applied to forecast maproom for now, to cleanly layout callback that take care of location selection, then callback that take location to make a local graph (or return an error if outside domain or no data).
Points of concern:
1. I am really not sure I am doing the right thing to get the Marker position back
2. This seems to force LayerGroup to be for the Marker and only the Marker
3. Once cleaned up, it might make sense to factor things out for a generalized approach to apply to all maprooms
=> callback pathway for location and their graphs

onset_maproom/maproom.py
That had been done for forecast for a while. Now ported to onset.
=> error_fig is a pingrid feature

onset_maproom/agronomy.py, onset_maproom/tests/test_agronomy.py
For now, ignoring the possibilities of multiple years/growing-seasons.
Turns out that I forgot to clip the wb to 0 in the bucket step. wb can not be negative. I guess it would be more logical to clip et so that it can't be greater than sm(t-1) + peff(t) but that is not how Eunjin does it. She also sets wb to 0 if negative.
Also corrected some typos or practicalities.
After this PR, we can start build up the loop. So next should be Kc this time for real.
=> passing the bucket into a loop

fbfmaproom/fbf-update-data.py, fbfmaproom/fbfmaproom-sample.yaml
=> Niger enacts mon and chirp spi JAS

enacts/flex_fcst/maproom.py
This is meant to address this [comment](https://github.com/iridl/python-maprooms/pull/207#discussion_r999821139)
=> rainsing exception rather than returning error figure

fbfmaproom/data-conversion-scripts/ethiopia/southern-oromia-bad-years.py, fbfmaproom/fbfmaproom-sample.yaml, fbfmaproom/fbfmaproom.py
Initial, partial support for variables that are provided by region instead of gridded. Aggregation/projection from one admin level to another will follow in a later PR. The table is currently broken for Malawi for all levels except District. Dan's ok with that, he just wants to show a draft to get  feedback.
@kgraaf please review after the fact. I'm merging now so Dan can share it.
=> Obs per region

enacts/onset/agronomy.py, enacts/onset/tests/test_agronomy.py
This could actually be done vectorially directly on et, but that won't be true anymore when planting date is inferred by the algorithm, hence through the loop. That would be the next step.
=> adding Kc to the loop when planting date is given

fbfmaproom/data-conversion-scripts/niger/badyears.py, fbfmaproom/fbfmaproom-sample.yaml
Putting the data file in /data/aaron/fbf/original-data/niger.
=> new bad years for niger

fbfmaproom/data-conversion-scripts/malawi/malawi_crop.py
Data file is in /data/aaron/fbf/original-files/malawi.
=> zarrification script for malawi crop forecast

enacts/wat_bal/agronomy.py, enacts/wat_bal/tests/test_agronomy.py
those 2 files were changed by last PR merge, but then following PR merged moved them, keeping older versions
=> Rebase fix

fbfmaproom/__about__.py, fbfmaproom/fbfmaproom-sample.yaml, fbfmaproom/fbfmaproom.py
Cleaning up some shortcuts I took to get the onset and dry spell forecasts integrated in a hurry. No change in functionality.
=> Properly distinguish probability of exceedance from prob of non-exceedance

enacts/wat_bal/maproom_monit.py
=> latest spwb outputs pd and server/port config names changed

enacts/config-gmet.yaml, enacts/config-mali.yaml, enacts/config-nma.yaml, enacts/config-sng.yaml, enacts/config-zmd.yaml, enacts/enactstozarr.py, enacts/onset/layout.py, enacts/onset/maproom.py
improving the file for enacts zarr conversion
=> Enactstozarr

enacts/wat_bal/agronomy.py, enacts/wat_bal/tests/test_agronomy.py
This is the last component to cover what was implemented in Ingrid. I also worked a bit on the documentation throughout.
Next steps would be to make a multi-year version of this one year function.
Subsidiary question: should outputs be a tuple or a dataset of variables?
=> Ks implementatio, with doc and tests

enacts/app.py, enacts/onset/layout.py, enacts/onset/maproom.py, enacts/wat_bal/maproom_monit.py
Now adding the tabbed local graphs for the length of the season, with custom hover data. Can be run for ZMD. Might be a bit slow on devi.
Turned out I had to make corrections to the work just previously merged on the global config set up. I thought I had test that but maybe not... Or I had rebased poorly... (?)
=> local time series for Season Length

enacts/wat_bal/config-defaults.yaml, enacts/wat_bal/globals_.py, enacts/wat_bal/layout_monit.py, enacts/wat_bal/maproom_monit.py
I had not done adjusted this app to the new config system at the time (because I was in a hurry likely) and now there are also the new colorscales to adjust.
For Aaron to review and Drew to be aware as this may bare on how they set up their Crop Maproom.
=> adjusting to new config and colorscale settings

fbfmaproom/fbfmaproom.py
test_table_cb goes from 4.5s to 1.5s.
=> Speed up table generation by avoiding redundant shape queries

fbfmaproom/fbfmaproom.py
This is a small step along the way to being able to display any variable on the map, and to stop faking the  dates of variables whose true time is different from the target season. It replaces the config dictionary representing a dataset with an object. There are two classes, one for obs datasets and one for forecast datasets, that both implement the same interface.
A future step will to be to describe a table column as a Dataset plus slicing criteria and an optional time shift. Trying to
=> Replace dataset config dictionary with object

enacts/monthly/maproom.py
=> this is how one returns empty tiles

fbfmaproom/fbf-update-data.py
Adding a copy of the forecast dataset for training purposes, and removing download caching that does more harm than good.
=> Lesotho training

fbfmaproom/fbf-update-data.py
Catalog entry change to follow.
=> Get Niger JJASO forecast from /home/.aaron

enacts/crop_suitability/layout_crop_suit.py, enacts/crop_suitability/maproom_crop_suit.py
tested on the Ethiopian config (so tested on one case only)
=> proper reading of data from config files

enacts/CHANGELOG.md, enacts/app.py, enacts/config-bd.yaml, enacts/config-defaults.yaml, enacts/config-gmet.yaml, enacts/config-zmd.yaml, enacts/crop_suitability/maproom_crop_suit.py, enacts/flex_fcst/__init__.py, enacts/flex_fcst/layout.py, enacts/flex_fcst/maproom.py, enacts/globals_.py, enacts/homepage.py, enacts/monthly/maproom.py, enacts/onset/maproom.py, enacts/wat_bal/maproom_monit.py, pingrid/impl.py
Supports multiple instances of the flex forecast maproom.
I have to do this for Lesotho urgently. I don't recommend adapting any other countries yet, as I plan to do more simplification once the Lesotho deadline is taken care of.
Probably easiest to read one commit at a time, and suppressing whitespace differences when viewing the commit "Support multiple instances of flex forecast maproom."
AccompanyingLesotho PR: https://bitbucket.org/iridl/python_maproom_lesotho/pull-requests/3
=> Multi forecast 2

fbfmaproom/__about__.py, fbfmaproom/data-conversion-scripts/djibouti/bad-years-jjas.py, fbfmaproom/data-conversion-scripts/djibouti/dummy-forecast.py, fbfmaproom/data-conversion-scripts/zarrify-forecast.py, fbfmaproom/fbf-update-data.py, fbfmaproom/fbfmaproom-sample.yaml, fbfmaproom/fbfmaproom.py
Adding a JJAS season for Djibouti. This wasn't entirely trivial, because it was the first time we have set up a season that wasn't three months long, and that assumption was baked in in a couple places.
Also adding WRSI for OND and JJAS. FEWS in the DL doesn't have a rangeland WRSI product for MAM, and the agricultural WRSI products rarely have values over Djibouti.
https://trello.com/c/Y9Y12Kaa/38-djibouti-wrsi
https://trello.com/c/mu7bvfDN/39-djibouti-jjas
I recommend reading one commit at a time.
=> Djibouti JJAS; Djibouti WRSI

fbfmaproom/__about__.py, fbfmaproom/tests/test_pingrid.py, pingrid/impl.py
`test_deep_merge_list_in_dict` is the case that was failing, causing the external staging fbfmaproom server to fail to start.
=> Fix bug in deep_merge

fbfmaproom/fbfmaproom-sample.yaml
See https://trello.com/c/5V5chmVs/49-clean-up-ethiopia-datasets
=> Remove unused Ethiopia datasets

fbfmaproom/fbfmaproom-sample.yaml
The files don't exist yet, will be generated as part of the training next week. I'm just getting the application ready to receive them.
=> Add Madagascar forecasts v3

pepsico/isimiptozarr.py
Thus attrs belong to xda[coord] and not at all to coord
=> coord is a string

fbfmaproom/fbfmaproom-sample.yaml
Currently running on 
http://shortfin01.iri.columbia.edu:9998/fbfmaproom/ethiopia-ond
http://shortfin01.iri.columbia.edu:9998/fbfmaproom/southern-oromia-ond
=> Ethiopia OND v2

fbfmaproom/fbfmaproom-sample.yaml
Changed default dropdown value to pnep v3 from pnep.
=> Updated to pnep v3

fbfmaproom/data-conversion-scripts/zarrify-forecast.py, fbfmaproom/fbf-update-data.py, fbfmaproom/fbfmaproom-sample.yaml
Continuing on the work started by Xandre.
There will also be a corresponding dlentries PR.
=> Guatemala JJA

fbfmaproom/fbf-update-data.py, fbfmaproom/fbfmaproom-sample.yaml
Necessary because we don't have full data for the "previous OND season's rainfall" variable during the issue month of December
=> Added CHIRP ON observational dataset to ethiopia and southern-oromia

fbfmaproom/data-conversion-scripts/zarrify-forecast.py, fbfmaproom/fbf-update-data.py
Also moving top-level commands into a __main__ block; that's in a separate commit for your reviewing convenience.
=> Set umask before creating files/directories in /data/aaron/fbf-candidate

pepsico/projections/maproom.py, pingrid/impl.py
Gives more appropriate color scales variable-wise (in spite of the name of the PR, I did mean to deal with all variables in it). Something seems off with respect to map_attributes factorization; how min/max are obtained; and how min/max values are passed on. But I can't put my finger on it as of now. Maybe it's ColorScale that needs a bit more functionality. Anyway, it's not important unless someone sees something obviously cleaner to do (that is not a major project).
=> Prcp anomaly cs

pepsico/projections/layout.py, pepsico/projections/maproom.py
Series of commits to provide a download button to download csv identical to data in ts graph.
=> Downloadcsv

fbfmaproom/assets/style.css, fbfmaproom/fbflayout.py, fbfmaproom/fbftable.py
Fixes a bunch of UI bugs and annoyances, particularly on small screens: double scrollbars, too little space for the scrollable part of the table, disclaimer doesn't stay in place, disclaimer obscures important text, menu items overlap, inconsistent fonts.
=> Layout refinement

pepsico/config-defaults.yaml, pepsico/monthly_average.py, pepsico/projections/layout.py, pepsico/projections/maproom.py
Sets up admin layers as they are in classic Maprooms. Different foci for different regions.
=> admin per region

fbfmaproom/fbf-update-data.py, fbfmaproom/fbfmaproom-sample.yaml
Hi Aaron,
The forecast generated with the new link much faster. However I was using the bad years from DJF over here and for some reason that's not working, any idea why? I've attached the the error below for you to see.
@dantesab9  I've pushed the updated config file to Madagascar's repository if you need to discuss it next week with the MET department and Azhar
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/magima/python-maprooms/fbfmaproom/fbfmaproom.py", line 1160, in table_cb
main_df, summary_df, thresholds = generate_tables(
File "/home/magima/python-maprooms/fbfmaproom/fbfmaproom.py", line 390, in generate_tables
basic_ds = fundamental_table_data(
File "/home/magima/python-maprooms/fbfmaproom/fbfmaproom.py", line …
=> Updated fbf-update-data.py and fbfmaproom-sample.yaml for Madagascar NDJ

enacts/config-test-enacts.yaml, enacts/monthly/__init__.py, enacts/monthly/layout.py, enacts/monthly/maproom.py
This concludes that. (Also zarred ANACIM dekadal data in the process)
=> Registermon

pepsico/projections/layout.py, pepsico/projections/maproom.py
both for map and the time series. Now download data in graph returns all models regardless of the model choice. Surprisingly doesn't seem to increase much wait time for either map or ts to show up...
=> multi-model averge option

fbfmaproom/__about__.py, fbfmaproom/fbflayout.py, fbfmaproom/fbfmaproom.py, fbfmaproom/tests/test_fbfmaproom.py
=> CSV validation tool

enacts/calc.py, enacts/config-test-synt.yaml, enacts/crop_suitability/maproom_crop_suit.py, enacts/flex_fcst/maproom.py, enacts/monthly/maproom.py, enacts/onset/maproom.py, enacts/wat_bal/maproom_monit.py
A rectangle contained in bbox partitioned by its SW-NE diagonal
=> synthetic geometries

fbfmaproom/fbfmaproom-sample.yaml
Added JAS v3 for Djibouti.
Best,
Nitin
=> Update fbfmaproom-sample.yaml to include JAS v3 for Djibouti

fbfmaproom/fbfmaproom-sample.yaml
Hi @aaron-kaplan , I am adding here the new forecast version to display the newly synced data from DGM. I added a minor correction for the label describing version 2 as well.
=> Adding new version of the NDJ forecast for Madagascar AA

fbfmaproom/fbfmaproom-sample.yaml
Hi Aaron,
I've added bad years version 3 (bad-years-ndj-v3.zarr) for Madagascar NDJ. Please sync the data as well for production.
Best,
Nitin
=> Adding Bad Years Version 3 for Madagascar MDJ
